// * File generated by SourceCombiner.exe using 5 source files.
// * Created On: 17/10/2020 16:58:59
using System;
using System.Reflection;
using System.Text;
//*** SourceCombiner -> original file ChuckNorrisEncoder.cs ***
namespace CodinGameOutput
{
    public static class ChuckNorrisEncoder
    {
        public static string Encode(string message)
        {
            var binary = ToBinary(message);
            var sb = new StringBuilder();
            ComputeEncoding(sb, binary);
            return sb.ToString();
        }
        private static string ToBinary(string message)
        {
            string result = string.Empty;
            foreach (var ch in message)
            {
                result += Convert.ToString(ch, 2).PadLeft(7, '0');
            }
            return result;
        }
        private static void ComputeEncoding(StringBuilder sb, string binary)
        {
            var current = ' ';
            for (int i = 0; i < binary.Length; i++)
            {
                if (binary[i] == current)
                    sb.Append("0");
                else if (binary[i] == '1')
                    sb.Append(i == 0 ? "0 0" : " 0 0");
                else
                    sb.Append(i == 0 ? "00 0" : " 00 0");
                current = binary[i];
            }
        }
    }
}
//*** SourceCombiner -> original file Program.cs ***
/**
 * Auto-generated code below aims at helping you parse
 * the standard input according to the problem statement.
 **/
namespace CodinGameOutput
{
    public class Solution
    {
        static void Main(string[] args)
        {
            string MESSAGE = Console.ReadLine();
            var result = ChuckNorrisEncoder.Encode(MESSAGE);
            Console.WriteLine(result);
        }
    }
}
//*** SourceCombiner -> original file .NETCoreApp,Version=v2.0.AssemblyAttributes.cs ***
// <autogenerated />
//*** SourceCombiner -> original file .NETCoreApp,Version=v3.1.AssemblyAttributes.cs ***
// <autogenerated />
//*** SourceCombiner -> original file .NETCoreApp,Version=v3.1.AssemblyAttributes.cs ***
// <autogenerated />
