// * File generated by SourceCombiner.exe using 3 source files.
// * Created On: 23/08/2020 15:46:23
using System;
using System.Reflection;
//*** SourceCombiner -> original file Program.cs ***
namespace CodinGameOutput
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
//*** SourceCombiner -> original file .NETCoreApp,Version=v2.0.AssemblyAttributes.cs ***
// <autogenerated />
//*** SourceCombiner -> original file .NETCoreApp,Version=v3.1.AssemblyAttributes.cs ***
// <autogenerated />
